In [12]:
# 多层神经网络计算梯度案例
# x中的特征数据批量定义，batch=3
import torch
    
x = torch.randn(3,requires_grad=True)
#x = {x1,x2,x3}
# 第二层定义
y = x + 2
# 输出层定义
z = 3 * y ** 2 # 3倍的y的平方

#建立J函数，可向后传播(此处J=z.mean()，该函数无实际意义
z = z.mean() # z = (z1+z2+z3)/3 只有标量可以向后传播

In [13]:
print(x)
print(y)
print(z)

tensor([0.1716, 0.2358, 0.0159], requires_grad=True)
tensor([2.1716, 2.2358, 2.0159], grad_fn=<AddBackward0>)
tensor(13.7783, grad_fn=<MeanBackward0>)


In [14]:
z.backward()
print(x.grad)
print(2 * (x + 2))


tensor([4.3432, 4.4716, 4.0317])
tensor([4.3432, 4.4716, 4.0317], grad_fn=<MulBackward0>)
