In [8]:
import torch
x = torch.tensor(1.)
y = torch.tensor(2.)

w = torch.randn(1,requires_grad=True)
print(x,y)
print(w)

def forward(x,w):
    pred =  w * x
    return pred

predict = forward(x,w)
print(predict)

tensor(1.) tensor(2.)
tensor([-0.5636], requires_grad=True)
tensor([-0.5636], grad_fn=<MulBackward0>)


In [9]:
loss = (predict-y) ** 2
print(loss)

tensor([6.5721], grad_fn=<PowBackward0>)


In [10]:
loss.backward()
print(w.grad)

tensor([-5.1272])
