In [53]:
import torch

m1 = torch.randn(1,requires_grad=True)
m2 = torch.randn(1,requires_grad=False)
b1 = torch.randn(1)
b2 = torch.randn(1)

In [54]:
print(m1)
print(m2)
print(b1,b2)

tensor([1.6874], requires_grad=True)
tensor([-1.5371])
tensor([-0.6838]) tensor([0.1900])


In [55]:
def forward1(x):
    global m1,b1
    return m1 * x + b1
def forward2(x):
    global m2,b2
    return m2 * x + b2
data  = [ [2,5] ] # m = 2 ,b =1 最佳
x = data[0][0]
y = data[0][1]
print(x,y)

2 5


In [56]:
# 1.前向传播,构建了计算图
predipt1 = forward1(x)
predict2 = forward2(x)

# 构造损失(代价)函数
loss1 = ( y - predipt1 ) ** 2
loss2 = ( y - predict2 ) ** 2

In [57]:
# 查看复合函数是否能够自动求偏导数
print(loss1.grad_fn)
print(loss2.grad_fn)

loss1.backward()

None


In [58]:
#查看m1和m2的偏导值
print(m1.grad,b1.grad,m2.grad)
print(m1.grad)
print(m2.grad)

tensor([-9.2356]) None None
tensor([-9.2356])
None


In [59]:
mpd1 =  2 * (y - (m1 * x +b1)) * (-1 * x )
print(mpd1)
print((mpd1 == m1.grad))

tensor([-9.2356], grad_fn=<MulBackward0>)
tensor([True])
