In [2]:
import torch

m1 = torch.randn(1,requires_grad=True)
m2 = torch.randn(1,requires_grad=False)
b1 = torch.randn(1)
b2 = torch.randn(1)

In [3]:
print(m1)
print(m2)
print(b1,b2)

tensor([-0.3759], requires_grad=True)
tensor([0.2375])
tensor([1.1335]) tensor([-1.3469])


In [4]:
def forward1(x):
    global m1,b1
    return m1 * x + b1
def forward2(x):
    global m2,b2
    return m2 * x + b2
data  = [ [2,5] ] # m = 2 ,b =1 最佳
x = data[0][0]
y = data[0][1]

In [5]:
# 1.前向传播,构建了计算图
predipt1 = forward1(x)
predict2 = forward2(x)

# 构造损失(代价)函数
loss1 = (y-predipt1)**2
loss2 = (y -predict2)**2

In [7]:
# 查看复合函数是否能够自动求偏导数
print(loss1.grad_fn)
print(loss2.grad_fn)

None


In [8]:
#查看m1和m2的偏导值
print(m1.grad)
print(m2.grad)

tensor([-18.4731])
None


In [9]:
mpd1 =  2 * (y - (m1 * x +b1)) * (-1 * x )
print((mpd1 == m1.grad))

tensor([True])


In [6]:
# 2.向后传播
# 向后传播时自动计算梯度
loss1.backward()
loss2.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn