In [1]:
#梯度下降算法
import  numpy as np
import matplotlib.pyplot as plt
import itertools

data = np.array(
    [
        [80,200],
        [95,230],
        [104,245],
        [112,247],
        [125,259],
        [135,262]
    ]
)

In [2]:
# 初始化参数
m = 1
b = 1
lr  = 0.00001

# 梯度下降的函数
# 当前的m，b和数据 data，学习率lr
def gradientdecent(m,b,data,lr):
    loss,mpd,bpd = 0,0,0
    # loss 均方误差 ，mpd为m的偏导数，bpd为b的偏导数
    for xi,yi in data:
        loss += (m * xi + b - yi)**2
        bpd += (m * xi + b - yi) * 2
        mpd += (m * xi + b - yi) * 2 * xi

    #更新m,b
    N = len(data)
    loss = loss / N
    mpd = mpd / N
    bpd = bpd / N
    m = m - mpd * lr
    b = b - bpd * lr
    return loss,m,b


for ecoch in range(30000000):
    mse,m,b = gradientdecent(m,b,data,lr)
    if(ecoch % 100000) == 0:
        print(f"loss={mse:.4f},m={m:.4f},b={b:.4f}")

loss=17206.3333,m=1.2848,b=1.0026
loss=408.1946,m=2.1179,b=7.5338
loss=370.0703,m=2.0626,b=13.7073
loss=335.9246,m=2.0102,b=19.5497
loss=305.3423,m=1.9607,b=25.0789
loss=277.9514,m=1.9138,b=30.3117
loss=253.4190,m=1.8694,b=35.2639
loss=231.4467,m=1.8274,b=39.9506
loss=211.7673,m=1.7876,b=44.3860
loss=194.1417,m=1.7500,b=48.5835
loss=178.3554,m=1.7144,b=52.5561
loss=164.2165,m=1.6807,b=56.3156
loss=151.5531,m=1.6488,b=59.8736
loss=140.2112,m=1.6186,b=63.2408
loss=130.0530,m=1.5901,b=66.4275
loss=120.9548,m=1.5630,b=69.4433
loss=112.8061,m=1.5375,b=72.2974
loss=105.5077,m=1.5133,b=74.9985
loss=98.9710,m=1.4903,b=77.5548
loss=93.1165,m=1.4687,b=79.9740
loss=87.8729,m=1.4481,b=82.2635
loss=83.1765,m=1.4287,b=84.4302
loss=78.9702,m=1.4103,b=86.4808
loss=75.2029,m=1.3929,b=88.4215
loss=71.8287,m=1.3765,b=90.2580
loss=68.8066,m=1.3609,b=91.9962
loss=66.0999,m=1.3462,b=93.6411
loss=63.6757,m=1.3322,b=95.1978
loss=61.5045,m=1.3190,b=96.6711
loss=59.5598,m=1.3065,b=98.0654
loss=57.8181,m=1.2947,

In [10]:
# 对四个张量自动赋值，并设置某个张量《例如m1)需要计算偏导数需要后向传播)
import torch
m1 = torch.randn((1),requires_grad=True)
m2 = torch.randn((1),requires_grad=False)
b1 = torch.randn((1))
b2 = torch.randn((1))

print(m1)
print(m2)
print(b1)
print(b2)

def forward1(x):
    global m1,b1
    return m1 * x + b1
def forward2(x):
    global m2,b2
    return m2 * x + b2
data = [2,5]
x = data[0]
y =data[1]

predict_fx1 = forward1(x)
predict_fx2 = forward2(x)

loss1 = (y - predict_fx1) ** 2
loss2 = (y - predict_fx2 )** 2

# 2.向后传播
# 向后传播时自动计算梯度
loss1.backward()
# loss2.backward()
print(loss1.grad_fn)
print(loss2.grad_fn)

print(m1.grad,b1.grad,m2.grad)
#手工计算m1的偏导值mpd1,并与m1.grad比较
mpd1 = 2 * (y -(m1 * x + b1)) * (-1 * x)

print(mpd1)
print(mpd1 == m1.grad)






tensor([0.1366], requires_grad=True)
tensor([0.5731])
tensor([-0.3024])
tensor([-0.5564])
None
tensor([-20.1173]) None None
tensor([-20.1173], grad_fn=<MulBackward0>)
tensor([True])
